name: wwwdeployicintr

services:
  postgres:
    image: postgres:16
    container_name: db-dokploy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dokploy}
      POSTGRES_DB: ${POSTGRES_DB:-dokploy}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-amukds4wi9001583845717ad2}
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    networks:
      - dokploy-network

  redis:
    image: redis:7
    container_name: db-dokploy-redis
    restart: unless-stopped
    volumes:
      - ./data/redis-data:/data
    networks:
      - dokploy-network

  dokploy:
    image: dokploy/dokploy:latest
    container_name: app-dokploy
    restart: unless-stopped
    environment:
      ADVERTISE_ADDR: ${ADVERTISE_ADDR:-159.69.219.251}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-your-secret-key-here}
    ports:
      - "10207:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/dokploy-data:/etc/dokploy
      - ./data/dokploy-docker-config:/root/.docker
    networks:
      - dokploy-network
    depends_on:
      - db-dokploy-postgres
      - db-dokploy-redis

  traefik:
    image: traefik:v3.1.2
    container_name: app-dokploy-traefik
    restart: unless-stopped
    ports:
      - "10080:80"
      - "10443:443"
      - "10443:443/udp"
    volumes:
      - ./data/dokploy-data/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./data/dokploy-data/traefik/dynamic:/etc/dokploy/traefik/dynamic:ro
      - ./data/dokploy-data/traefik/acme.json:/etc/dokploy/traefik/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dokploy-network
    depends_on:
      - app-dokploy

networks:
  dokploy-network:
    driver: bridge